import {useEffect, useRef, useState } from 'react';

interface Minister {
  id?: string; // Assuming id is optional as it's generated by the backend
  name: string;
  info: string;
}

interface MinisterFormFields {
  name: string;
  info: string;
}

function App() {
  const [ministerformFields, setMinisterFormFields] = useState<MinisterFormFields>({
      info: 'Senior Pastor Springs of Hope Christian Ministries',
      name: 'Pastor Mrs. Grace Lasisi',
    });
    
    useEffect(() => {
        console.log('Updated ministerformFields:', ministerformFields);
    }, [ministerformFields]);
    
  
    const [currentOutput, setCurrentOutput] = useState('');
    
    const [showslidecontrols, setShowSlideControls] = useState(true);
    const [valid_minister_info, setValidMinisterInfo] = useState('');
    
    const [ministerdb, setMinisterDB] = useState<Minister[]>([{ // Use Minister interface
      name: 'Pastor Mrs. Grace Lasisi',
      info: 'Senior Pastor Springs of Hope Christian Ministries',
    }]);

  const [new_minister, setNewMinister] = useState<Minister>({ // Use Minister interface
    name: '',
    info: '',
  });

  // Autocomplete state
  const [searchTerm, setSearchTerm] = useState('');
  const [suggestions, setSuggestions] = useState<Minister[]>([]);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const searchContainerRef = useRef<HTMLDivElement>(null);


  useEffect(() => {
    const fetchSuggestions = async () => {
      if (searchTerm.trim() === '') {
        setSuggestions([]);
        setShowSuggestions(false);
        return;
      }
      try {
        const response = await fetch(`/api/search_minister?q=${encodeURIComponent(searchTerm)}`, {
          method: 'POST', // As defined in backend
          headers: { 'Content-Type': 'application/json' },
        });
        if (response.ok) {
          const data: Minister[] = await response.json();
          setSuggestions(data);
          setShowSuggestions(data.length > 0);
        } else {
          setSuggestions([]);
          setShowSuggestions(false);
          console.error('Error fetching suggestions:', response.statusText);
        }
      } catch (error) {
        setSuggestions([]);
        setShowSuggestions(false);
        console.error('Error fetching suggestions:', error);
      }
    };

    const debounceFetch = setTimeout(() => {
      fetchSuggestions();
    }, 300); // Debounce API calls

    return () => clearTimeout(debounceFetch);
  }, [searchTerm]);

  const handleSuggestionClick = (minister: Minister) => {
    setMinisterFormFields({ name: minister.name, info: minister.info });
    setSearchTerm('');
    setSuggestions([]);
    setShowSuggestions(false);
  };
  
  // Handle clicks outside the search container to close suggestions
  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (searchContainerRef.current && !searchContainerRef.current.contains(event.target as Node)) {
        setShowSuggestions(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, [searchContainerRef]);

  
  const getDynamicValue = async (dynamic_value: string) => {
    const res = await fetch('/fs-api/', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ action: 'get_dynamic_value', value: dynamic_value }),
    });

    const data = await res;
    // setResult(data);
    console.log('Dynamic Value');
    console.log(data.text());
    return data;
  }

  useEffect(() => {
    // Call the function to get the dynamic values
    getDynamicValue('current_minister_info');
    getDynamicValue('current_minister_name');
    getCurrentSlideInfo();

    refreshMinisterInfo();
  }
    , []);



  const getCurrentSlideInfo = async () => {
    // Retrieve the current slide name and text from 2 separate API calls and return both
    const resp_slide_text = await fetch('/fs-api/', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ action: 'get_output_slide_text' }),
    })

    const data = await resp_slide_text.json();
    console.log('Current Slide Info');
    console.log(data.data);
    setCurrentOutput(data.data);
    return;
  };

  const handleButtonClick = async (button_value: string) => {
    // e.preventDefault();
    // e.target.classList.add('bg-gray-900 border-2 border-amber-300');
    const res = await fetch('/fs-api/', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ action: button_value }),
    })

    const data = await res;
    console.log('Button Click');
    console.log(data);
    getCurrentSlideInfo();
    return
  }

  const refreshMinisterInfo = async () => {
    const res = await fetch('/api/get_ministers', {
      method: 'GET',
      headers: { 'Content-Type': 'application/json' },
      // body: JSON.stringify({ action: 'get_minister', value: 'current_minister_info' }),
    });
    const data = await res.json();
    console.log('Minister Info');
    console.log(data);
    setMinisterDB(data);
  }

  const callApiVariableUpdate = (data: any[] | undefined) => {

    // Loop through the data entries and run the api call using the data
    data?.forEach((each_variable_update) => {
      console.log(each_variable_update);
      const res = fetch('/fs-api', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'change_variable', ...each_variable_update })
      });

      res.then((response) => {
        if (response.ok) {
          console.log('Minister updated successfully');
        } else {
          console.error('Error updating minister');
        }
      }
      ).catch((error) => {
        console.error('Error:', error);
      })
    });

  };

  // Function can take a form event or a button event
  const handleMinisterUpdate = (e?: React.FormEvent<HTMLFormElement>) => {
    e?.preventDefault();

    // When no event is passed, it means the function is called from the clear button
    // and we need to set the ministerformFields to the default values

    if (e?.target === undefined) {
      console.log('Resetting minister form fields');
      setMinisterFormFields({ name: '', info: '' });
    }else {
      console.log('Updating minister form fields with form input.');
    }
    
    console.log('Minister Update');
    console.log(ministerformFields);


    const api_data: { name: string; key: string; value: string }[] = [];
    api_data.push({
      name: 'current_minister_info',
      key: 'value',
      value: ministerformFields.info
    });

    // Loop through the data entries and run the api call using the data
    api_data.push({
      name: 'current_minister_name',
      key: 'value',
      value: ministerformFields.name
    });

    // Loop through the data entries and run the api call using the data
    callApiVariableUpdate(api_data)

    setValidMinisterInfo('...');

  };

  const addNewMinister = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    console.log('Minister Update');
    console.log(new_minister);

    const res = fetch('/api/add_minister', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ ...new_minister })
    });

    res.then((response) => {
      if (response.ok) {
        console.log('Minister updated successfully');
      } else {
        console.error('Error updating minister');
      }
    }
    ).catch((error) => {
      console.error('Error:', error);
    })


    refreshMinisterInfo();
  };


  return (
    <div style={{ padding: '2rem' }}>
      <h1 className='text-3xl'>Service Manager</h1>
      <h2 className='text-md'>Today: {'Sunday Service'}</h2>
      <p className='text-sm mt-1'>
        <span className='mr-2'><span className='text-gray-400'>Current Event: </span><span className='font-bold'>{'Cast your burdens'}</span></span>
        <span className='mr-2'><span className='text-gray-400'>Next Event: </span><span className='font-bold'>{'Praise and Worship'}</span></span>
      </p>
      <div className='grid md:grid-cols-1 lg:grid-cols-2 gap-4'>
        <div>
        <div>
        {/* Autocomplete Search Input */}
        <div ref={searchContainerRef} style={{ position: 'relative', marginBottom: '1rem' }}>
          <label className='mt-4 mb-2 text-sm block'>Search Minister</label>
          <input
            type="text"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            onFocus={() => setShowSuggestions(suggestions.length > 0)}
            placeholder="Type to search for a minister..."
            className='border-2 border-gray-300 rounded p-1 text-sm w-full'
            style={{ marginBottom: '0.25rem' }}
          />
          {showSuggestions && suggestions.length > 0 && (
            <ul style={{
              position: 'absolute',
              top: '100%',
              left: 0,
              right: 0,
              border: '1px solid #ccc',
              backgroundColor: 'white',
              listStyleType: 'none',
              margin: 0,
              padding: 0,
              zIndex: 1000,
              maxHeight: '200px',
              overflowY: 'auto',
              boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
            }}>
              {suggestions.map((minister, index) => (
                <li
                  key={minister.id || index} // Use minister.id if available, otherwise index
                  onClick={() => handleSuggestionClick(minister)}
                  style={{ padding: '0.5rem', cursor: 'pointer', borderBottom: '1px solid #eee' }}
                  className='hover:bg-gray-100'
                >
                  {minister.name} <span style={{fontSize: '0.8em', color: '#666'}}>({minister.info})</span>
                </li>
              ))}
            </ul>
          )}
        </div>

        <form onSubmit={handleMinisterUpdate}>
          <div className='flex flex-col justify-start'>
            <label className='mt-4 mb-2 text-sm'>Current Minister Info</label>
            <div className='mb-4 flex'>
              <input
                type="text"
                value={ministerformFields.info}
                name="current_minister_info"
                className='border-2 border-gray-300 rounded p-1 mr-2 text-sm w-3xl'
                onChange={(e) => setMinisterFormFields((prevNewMinister) => ({
                  ...prevNewMinister,
                  info: e.target.value,
                }))}
                placeholder="Minister Info"
              />
              <input
                type="text"
                name="current_minister_name"
                value={ministerformFields.name}
                className='border-2 border-gray-300 rounded p-1 mr-2 text-sm w-3xl'
                onChange={(e) => setMinisterFormFields((prevNewMinister) => ({
                  ...prevNewMinister,
                  name: e.target.value,
                }))}
                placeholder="Minister Name"
              />
              <button type="submit" name='submit' className='bg-gray-500 rounded text-white px-4 py-1 mr-2 hover:bg-blue-700 cursor-pointer'>Submit</button>
              <button type="button" name='clear' className='bg-red-400 rounded text-white px-4 py-1 hover:bg-blue-700 cursor-pointer' onClick={() => handleMinisterUpdate()}>Clear</button>
            </div>
            <div className='flex items-center rounded bg-gray-700 text-gray-400 p-1'>{valid_minister_info}</div>
          </div>
        </form>

        <form onSubmit={addNewMinister}>
          <div className='flex flex-col justify-start mt-2'>
            <label className='mt-4 mb-2 text-sm'>Add New Minister</label>
            <div className='mb-4 flex'>
              {/* input field to add new minister info */}
              <input
                type="text"
                name="add_minister_info"
                value={new_minister.info}
                className='border-2 border-gray-300 rounded p-1 mr-2 text-sm w-3xl'
                onChange={(e) => setNewMinister((prevNewMinister) => ({
                  ...prevNewMinister,
                  info: e.target.value,
                }))}
                placeholder="Minister Info"
              />
              {/* input field to add new minister name */}
              <input
                type="text"
                name="add_minister_name"

                value={new_minister.name}
                className='border-2 border-gray-300 rounded p-1 mr-2 text-sm w-3xl'
                onChange={(e) => setNewMinister((prevNewMinister) => ({
                    ...prevNewMinister,
                    name: e.target.value,
                }))}
                placeholder="Minister Name"

              />
              <button type="submit" className='bg-gray-700 rounded text-white px-4 py-1 hover:bg-blue-700 cursor-pointer'>Add</button>
            </div>
            <div className='flex items-center rounded bg-gray-700 text-gray-400 p-1'>{JSON.stringify(ministerdb)}</div>
          </div>
        </form>
        </div>

        <div className='flex flex-col justify-start row-span-2'>
          <div className="flex flex-row justify-between items-baseline mb-1">
            <label className='text-sm'>Current Slide</label>
            <button onClick={getCurrentSlideInfo} className='p-1 rounded text-xs bg-amber-600 h-8'>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="size-6" alt-text="Refresh SlideInfo">
                <path strokeLinecap="round" strokeLinejoin="round" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0 3.181 3.183a8.25 8.25 0 0 0 13.803-3.7M4.031 9.865a8.25 8.25 0 0 1 13.803-3.7l3.181 3.182m0-4.991v4.99" />
              </svg>
            </button>
          </div>
          <div className='mb-4 flex'>
            <div className='rounded border-2 border-gray-700 p-2 text-sm w-full min-h-2'>
              {currentOutput}
            </div>
          </div>
        </div>

        <div className='flex flex-col justify-start'>
          <label className='mt-4 mb-2 text-sm'>Cue Slides</label>
          <div className='mb-4 flex'>
            <input type='text' className='border-2 border-gray-300 rounded p-1 mr-2 text-sm' placeholder='Search Slide' />
          </div>
        </div>
      </div>
      <div className="grid">
        <div className='flex items-center justify-between fixed bottom-0 right-0 p-2 text-gray-100 text-sm border-t-cyan-100 w-full bg-gray-900'>
          {showslidecontrols ? (<div className='flex'>
            <button
              onClick={() => { setShowSlideControls(true) }}
              className='bg-gray-500 hover:bg-blue-700 text-black hover:text-white font-bold py-1 px-2 rounded cursor-pointer mr-2'
            >
              <span>&lt;</span><span className='hidden md:hidden'>Hide Controls</span>
            </button>
            <button
              onClick={() => handleButtonClick('previous_slide')}
              className='bg-red-500 hover:bg-blue-700 text-black hover:text-white font-bold py-1 px-2 rounded cursor-pointer mr-2'
              value={'previous_slide'}
            >
              Previous Slide
            </button>
            <button
              onClick={() => handleButtonClick('next_slide')}
              className='bg-green-500 hover:bg-blue-700 text-black hover:text-white font-bold py-1 px-2 rounded cursor-pointer'
              value={'next_slide'}
            >
              Next Slide
            </button>
          </div>) : <>
            <button onClick={() => { setShowSlideControls(true) }}>
              <span className='text-sm text-gray-400'>Show Slide Controls</span>
            </button>
          </>
          }
          <p className='sm:hidden'>
            <strong>Minister Info:</strong> {JSON.stringify(ministerformFields)}
          </p>
        </div>
      </div>
      {/* 
      {result && (
        <pre style={{ marginTop: '1rem' }}>
          {JSON.stringify(result, null, 2)}
        </pre>
      )} */}
    </div>
  );
}

export default App;
